stages:
    - build
    - test


ubuntu_test:
    stage: test
    image: "registry.gitlab.atp-fivt.org/tpos2022/shimanskijvl-practice/ubuntu_test"
    script:
        - cd autocontrast
        - pytest autocontrast/autocontrast_test.py
    rules:
        - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"'


centos_test:
    stage: test
    image: "registry.gitlab.atp-fivt.org/tpos2022/shimanskijvl-practice/centos_test"
    script:
        - cd autocontrast
        - pytest autocontrast/autocontrast_test.py
    rules:
        - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"'



ubuntu_build:
    stage: build
    image: "registry.gitlab.atp-fivt.org/tpos2022/shimanskijvl-practice/ubuntu_test"
    script:
        - cd autocontrast
        - pip install wheel
        - python3 -m setup.py bdist_wheel
    artifacts:
        paths:
            - dist/autocontrast-1.0.0-py3-none-any.whl
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_BRANCH == "staging"'


centos_build:
    stage: build
    image: "registry.gitlab.atp-fivt.org/tpos2022/shimanskijvl-practice/centos_test"
    script:
        - cd autocontrast
        - pip install wheel
        - python3 -m setup.py bdist_wheel
    artifacts:
        paths:
            - dist/autocontrast-1.0.0-py3-none-any.whl
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_BRANCH == "staging"'
