stages:
    - build
    - test


ubuntu_test:
    stage: test
    image: "registry.gitlab.atp-fivt.org/tpos2022/shimanskijvl-hwci/ubuntu_test"
    script:
        - cd autocontrast
        - pytest autocontrast_test.py
    rules:
        - if: '($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event" )'


centos_test:
    stage: test
    image: "registry.gitlab.atp-fivt.org/tpos2022/shimanskijvl-hwci/centos_test"
    script:
        - cd autocontrast
        - pytest autocontrast_test.py
    rules:
        - if: '($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event")'



ubuntu_build:
    stage: build
    image: "registry.gitlab.atp-fivt.org/tpos2022/shimanskijvl-hwci/ubuntu_test"
    script:
        - cd autocontrast
        - pip install wheel
        - python3 setup.py bdist_wheel
    artifacts:
        paths:
            - autocontrast/dist/cvutils-1.0.1-py3-none-any.whl
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "dev" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging" || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "staging" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")'
      #  - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_BRANCH == "staging"'


centos_build:
    stage: build
    image: "registry.gitlab.atp-fivt.org/tpos2022/shimanskijvl-hwci/centos_test"
    script:
        - cd autocontrast
        - pip install wheel
        - python3 setup.py bdist_wheel
    artifacts:
        paths:
            - autocontrast/dist/cvutils-1.0.1-py3-none-any.whl
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "dev" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging" || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "staging" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")'
     #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_BRANCH == "staging"'