---
- name: centos play
  hosts: centos
  become: yes
  tasks:
    - name: install pip on centos
      yum:
        name: ["epel-release", "python3-pip", "python3"]
        update_cache: yes 
    - name: upgrade pip on centos
      pip:
        name: pip
        extra_args: "--upgrade"
        executable: pip3
      vars:
        ansible_python_interpreter: /usr/bin/python3
    - name: Download .whl on centos
      get_url:
        url: https://gitlab.atp-fivt.org/TPOS2022/shimanskijvl-hwCI/-/jobs/8780/artifacts/file/autocontrast/dist/cvutils-1.0.1-py3-none-any.whl
        dest: /home/vagrant/
        validate_certs: False

- name: ubuntu play
  hosts: ubuntu
  become: yes
  tasks:
    - name: install pip on ubuntu
      apt:
        name: python3-pip
        update_cache: yes
    - name: Download .whl on ubuntu
      get_url:
        url: https://gitlab.atp-fivt.org/TPOS2022/shimanskijvl-hwCI/-/jobs/8779/artifacts/file/autocontrast/dist/cvutils-1.0.1-py3-none-any.whl
        dest: /home/vagrant/
        validate_certs: False

- name: all play
  hosts: all
  tasks:
    - name: Install dependencies
      pip:
        name: ["opencv-python", "numpy", "opencv-python-headless", "opencv-contrib-python-headless"]
        executable: pip3
        virtualenv_python: /usr/bin/python3
      vars:
        ansible_python_interpreter: /usr/bin/python3

  
    - name: Install autocontrast
      pip:
        name: /vagrant/autocontrast/dist/cvutils-1.0.1-py3-none-any.whl
        executable: pip3
      vars:
        ansible_python_interpreter: /usr/bin/python3
